version: '3'
services:
  app:
    image: microstudi/decidim-hacks:0.1
    # build: .
    # container_name: decidim-hacks
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
    ports:
      - 3000:3000
      - 3035:3035
      - 3035:3035/udp
    links:
      - pg
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=decidim_hacks_development
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  bundle: {}
  pg-data: {}
